// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/grpc/grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// найти сообщение по id - серверу
type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int64                  `protobuf:"varint,1,opt,name=textID,proto3" json:"textID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_proto_grpc_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageRequest) GetTextID() int64 {
	if x != nil {
		return x.TextID
	}
	return 0
}

// Вернуть сообщение - клиенту
type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int64                  `protobuf:"varint,1,opt,name=textID,proto3" json:"textID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_proto_grpc_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetTextID() int64 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *MessageResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Обновить сообщение - серверу
type UpdateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int64                  `protobuf:"varint,1,opt,name=textID,proto3" json:"textID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_proto_grpc_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMessageRequest) GetTextID() int64 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Удалить сообщение - серверу
type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int64                  `protobuf:"varint,1,opt,name=textID,proto3" json:"textID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_grpc_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMessageRequest) GetTextID() int64 {
	if x != nil {
		return x.TextID
	}
	return 0
}

// Создать сообщение - серверу
type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextID        int64                  `protobuf:"varint,1,opt,name=textID,proto3" json:"textID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_grpc_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *PostMessageRequest) GetTextID() int64 {
	if x != nil {
		return x.TextID
	}
	return 0
}

func (x *PostMessageRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_proto_grpc_grpc_proto protoreflect.FileDescriptor

const file_proto_grpc_grpc_proto_rawDesc = "" +
	"\n" +
	"\x15proto/grpc/grpc.proto\x12\x04grpc\"+\n" +
	"\x11GetMessageRequest\x12\x16\n" +
	"\x06textID\x18\x01 \x01(\x03R\x06textID\"U\n" +
	"\x0fMessageResponse\x12\x16\n" +
	"\x06textID\x18\x01 \x01(\x03R\x06textID\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"B\n" +
	"\x14UpdateMessageRequest\x12\x16\n" +
	"\x06textID\x18\x01 \x01(\x03R\x06textID\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\".\n" +
	"\x14DeleteMessageRequest\x12\x16\n" +
	"\x06textID\x18\x01 \x01(\x03R\x06textID\"X\n" +
	"\x12PostMessageRequest\x12\x16\n" +
	"\x06textID\x18\x01 \x01(\x03R\x06textID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text2\x8e\x02\n" +
	"\x04gRPC\x12<\n" +
	"\n" +
	"GetMessage\x12\x17.grpc.GetMessageRequest\x1a\x15.grpc.MessageResponse\x12B\n" +
	"\rUpdateMessage\x12\x1a.grpc.UpdateMessageRequest\x1a\x15.grpc.MessageResponse\x12B\n" +
	"\rDeleteMessage\x12\x1a.grpc.DeleteMessageRequest\x1a\x15.grpc.MessageResponse\x12@\n" +
	"\rCreateMessage\x12\x18.grpc.PostMessageRequest\x1a\x15.grpc.MessageResponseB\x11Z\x0fproto/grpc;grpcb\x06proto3"

var (
	file_proto_grpc_grpc_proto_rawDescOnce sync.Once
	file_proto_grpc_grpc_proto_rawDescData []byte
)

func file_proto_grpc_grpc_proto_rawDescGZIP() []byte {
	file_proto_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_proto_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grpc_grpc_proto_rawDesc), len(file_proto_grpc_grpc_proto_rawDesc)))
	})
	return file_proto_grpc_grpc_proto_rawDescData
}

var file_proto_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_grpc_grpc_proto_goTypes = []any{
	(*GetMessageRequest)(nil),    // 0: grpc.GetMessageRequest
	(*MessageResponse)(nil),      // 1: grpc.MessageResponse
	(*UpdateMessageRequest)(nil), // 2: grpc.UpdateMessageRequest
	(*DeleteMessageRequest)(nil), // 3: grpc.DeleteMessageRequest
	(*PostMessageRequest)(nil),   // 4: grpc.PostMessageRequest
}
var file_proto_grpc_grpc_proto_depIdxs = []int32{
	0, // 0: grpc.gRPC.GetMessage:input_type -> grpc.GetMessageRequest
	2, // 1: grpc.gRPC.UpdateMessage:input_type -> grpc.UpdateMessageRequest
	3, // 2: grpc.gRPC.DeleteMessage:input_type -> grpc.DeleteMessageRequest
	4, // 3: grpc.gRPC.CreateMessage:input_type -> grpc.PostMessageRequest
	1, // 4: grpc.gRPC.GetMessage:output_type -> grpc.MessageResponse
	1, // 5: grpc.gRPC.UpdateMessage:output_type -> grpc.MessageResponse
	1, // 6: grpc.gRPC.DeleteMessage:output_type -> grpc.MessageResponse
	1, // 7: grpc.gRPC.CreateMessage:output_type -> grpc.MessageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpc_grpc_proto_init() }
func file_proto_grpc_grpc_proto_init() {
	if File_proto_grpc_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grpc_grpc_proto_rawDesc), len(file_proto_grpc_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_proto_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_proto_grpc_grpc_proto_msgTypes,
	}.Build()
	File_proto_grpc_grpc_proto = out.File
	file_proto_grpc_grpc_proto_goTypes = nil
	file_proto_grpc_grpc_proto_depIdxs = nil
}
